### ISSUE TITLE
🐛 Character/Items image alignment issues

### ISSUE THREAD

**Issue by Nedok** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#104]
**Describe the bug**
Character, and item images is not centered (consistently) on character and item sheets. On character sheets, images are placed at top left always. For items, they are only centered horizontally.

Wide images:
![image](https://user-images.githubusercontent.com/5305496/115583245-0079ae00-a2ca-11eb-990c-7d101e4a86fb.png)

Tall Images:
![image](https://user-images.githubusercontent.com/5305496/115583705-6d8d4380-a2ca-11eb-9ddb-b6e607610dcb.png)

**Expected behavior**
All item and character images to be centered both vertically and horizontally to match the gray background gradient.

**Desktop:**
 - OS: Windows
 - Client Foundry Desktop app
 - Foundry Version 0.7.9
 - Forbidden Lands 5.1.2
 - Active Modules 0

**Comment by aMediocreDad** [comment]
Hiya,

This is something we will have to look at once the sheets are being redesigned (it's something we are in a preliminal stage of doing at the moment). As it stands the Charater sheet and the item sheets have been designed by different contributors and use two different structures. Ideally they would be aligned, but that requires work which will be redundant in a future iteration of the sheets.

**Comment by aMediocreDad** [comment]
I have made some smaller correction. But the underlying issue is still there. It won't get solved before we have the new character sheets up and running.
