### ISSUE TITLE
✨ Adding descriptions without artifact dice

### ISSUE THREAD

**Issue by Nedok** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#105]
**Is your feature request related to a problem? Please describe.**
Lets say my players find a nice bucket. I want to give the nice bucket a bit of flavor text, but to do that I have to transform this ordinary (but nice) bucket into a legendary artifact. Let's just say my party have a bit to many artifact by this point...

I like to give my players items with descriptions and appearance. However, the text fields to do so can only be accessed by giving the item an artifact bonus.

**Describe the solution you'd like**
I see two solutions to the problem.
1. Add a precistant description field for all items.
2. Add a "Normal Item+" category that shows the Artifact tab without adding an artifact dice to the object.

**Comment by aMediocreDad** [comment]
There is no really good way to solve this at the moment, without segmenting the item sheets in a way that makes it messy. 

E.g. do you want this for only gear? Or do you want it for Weapons and Armor too? We already have earlier contributions that remove most of the "fluff" textareas, so we need to work around these settings too.

**Comment by Nedok** [comment]
In my opinion, it have to apply to gear, weapons and armors.

Adding a "artifact-type that doesn't add dice" sound like a good ide to me, and cold solve my problem. As i see it, having the crafting tab on items isn't necessary for items with flavor text.

**Comment by aMediocreDad** [comment]
I have added a feature now that adds the extra diceless artifact category. 

A release will come up in a short while. If it solves your issue, please go ahead and mark it as closed.

**Comment by Nedok** [comment]
I tested it out and it solves my problem.
Me and my players compulsive bucket collecting thank you.
