### ISSUE TITLE
Minimized windows don't show the "close" button correctly.

### ISSUE THREAD

**Issue by MichalKolesinski** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#106]
Desktop 
 - OS: Both Win10 and Ubuntu 20.04
 - Client- Foundry Desktop app,
 - Foundry Version 0.7.9

![Screenshot1](https://user-images.githubusercontent.com/39199872/115952110-99841100-a4e4-11eb-92cc-464004d3b467.png)

**Comment by aMediocreDad** [comment]
This will be fixed in upcoming release.
