### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by stillday** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#108]
Is it planned that there will be a German translation? That would be great

**Comment by aMediocreDad** [comment]
Hi there!

This is a community developed system. As such we rely on the community to step up and contribute.

At the moment no Germans are working on the system or have indicated that they'd like to contribute to localization.

If you would like to help check out our CONTRIBUTING.md file. It should be in the root folder (apologies, I am on phone and so not able to link it that easily). Any help would be much appreciated!

**Comment by stillday** [comment]
Thx for your fast answer. i read later the file :)

**Comment by stillday** [comment]
i followed the link. but get a 404 error

**Comment by Raldanash** [comment]
If you are looking for help with a German translation, I am happy to chip in.

**Comment by aMediocreDad** [comment]
Hey @Raldanash Thank you for wanting to chip in!

@stillday Thanks for the heads up. I see the link is broken. I have updated the section with the correct link.

Here's a direct link to the gitlocalize page for German: https://gitlocalize.com/repo/6008/de/src/lang/en.json

**Comment by OnkelRod** [comment]
Hey, as I play with non-english speaking friends. I would like to contribute a little bit myself.

**Comment by narukaioh** [comment]
Thank you @OnkelRod too and welcome!

**Comment by OnkelRod** [comment]
Hey,

I went trough them an requested a review. Feedback will be very appreciated.
As the UHRWERK-Verlag has translated the books, will their translation be used or does Fria-Ligan have to do a whole new one just for Foundry vtt?

Have a nice weekend,

OnkelRod

**Comment by aMediocreDad** [comment]
> Hey,
> 
> I went trough them an requested a review. Feedback will be very appreciated.
> ...
> Have a nice weekend,
> 
> OnkelRod

Thanks @OnkelRod! I have gone ahead merged it:) I cannot comment on the German itself unfortunately. But the translations are there if anyone wants to suggest modifications. I'll however go ahead and close this issue.

It can be reopened if anyone has any comments on the translations.

> As the UHRWERK-Verlag has translated the books, will their translation be used or does Fria-Ligan have to do a whole new one just for Foundry vtt?

I cannot answer this unfortunately. I assume you are talking about the official content modules? If so you would have to direct your questions at [Free League Publishing](https://freeleaguepublishing.com/en/contact/). I was only commissioned to do the English language version, and I did some technical rewrites of the books to better adapt it to Foundry (e.g. I removed mentions of physical things like books, dice, sheets etc.).

Have a great rest of the weekend!

**Comment by OnkelRod** [comment]
> > As the UHRWERK-Verlag has translated the books, will their translation be used or does Fria-Ligan have to do a whole new one just for Foundry vtt?
> 
> I cannot answer this unfortunately. I assume you are talking about the official content modules? If so you would have to direct your questions at [Free League Publishing](https://freeleaguepublishing.com/en/contact/). I was only commissioned to do the English language version, and I did some technical rewrites of the books to better adapt it to Foundry (e.g. I removed mentions of physical things like books, dice, sheets etc.).
> 

@aMediocreDad  That was my Question, yes :) I will try and contact them. 
Thank you and good night.
