### ISSUE TITLE
Character generator no longer applies attributes after the last update.

### ISSUE THREAD

**Issue by MichalKolesinski** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#115]
Hi!
I have two instances of Foundry installed. On one I have updated the system and the bug showed itself. On the other one, with system version 5.2.1 all works as expected. I reinstalled the system and created clean world without any modules. The bug must be somehow related to the update.

**Comment by aMediocreDad** [comment]
Hey there! I actually found this one while I was working on 0.8 compatibility just now.

I have pushed a hotfix.

**Comment by MichalKolesinski** [comment]
Hi! Did it work? I updated the system, and still there's no change to the generator behavior. Have you removed the information that the changes cannot be reverted if somebody generates the character again? Do you think it's possible to reset talent and equipment list during generation, to prevent spamming objects? At the moment, if you go back to the generator and generate the character again, all the talents and gear entries remain.

**Comment by aMediocreDad** [comment]
Hi, that's strange. Try reinstalling the system. I reuploaded the release artifact, hopefully that should do it.

The warning that pops up is triggered by existing attributes. In the future I'll set a flag on the actor instead. So, you not getting that warning is not that strange considering the attributes weren't applied.

As for reseting talent and equipment, that's a good idea. I'll add it and do a patch in a day or two just in case there are other issues that crop up.
