### ISSUE TITLE
Macros for randomly generated Adventure Sites & NPCs, using the tables in the GMG

### ISSUE THREAD

**Issue by 9littlebees** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#119]
Similarly to the loot tables, it would be really great to include macros for randomly generated adventure sites and NPCs in the premium system module using the tables from chapter 8 in the GMG (pages 167-186).
Any plans to do so?

**Comment by aMediocreDad** [comment]
This issue is related to the official content modules, and would not be implemented in the system itself. I have therefore moved it to the content modules issue tracker: https://github.com/aMediocreDad/fbl-content-modules/issues/2
