### ISSUE TITLE
Character Generator does not record skills with spaces in name

### ISSUE THREAD

**Issue by LyonelMandrake** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#129]
When generating a character with the "chargen" if you have a childhood or a background that grants you "Animal Handling" it 
does not get recorded on your character sheet when you hit apply.

I suspect this might have to do with the space in the name of the skill.  After discovering this, I modified the dataset.json to add "Sleight of Hand" (the only other skill with a space in the name) and found the same behavior.  I did not see this behavior with any other skill in testing.

 - Windows 10
 - Chrome
 - Foundry Version 0.7.9
 - FBL System 5.3.5

**Comment by aMediocreDad** [comment]
Good catch! Thank you. This will be fixed in the next update.
