### ISSUE TITLE
Error importing premium modules

### ISSUE THREAD

**Issue by Eldebor** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#136]
Hi,

I've purchased the premium modules of Forbidden Lands but I get some error when importing the modules. I'm not sure if the problem is in this game system or in the modules. I've sent a mail to Free League support but I think that is worth it to add the issue here, just in case.

To avoid any backward issues I've created a clean world. Application and modules are in the last version:
- Foundry VTT: 0.8.7
- Forbidden Lands Game System: 6.0.1
- Forbidden Lands - Core Game: 1.2.0
- Forbidden Lands - Bitter Reach: 1.2.0
- Forbidden Lands - Raven's Purge: 1.2.0 

No other modules have been loaded.

I'm aware that Forbidden Lands premium modules show a Compatibility Risk tag. 

![image](https://user-images.githubusercontent.com/75694733/122802803-186baf00-d2c6-11eb-87c6-2a7f1b0e3a57.png)

When imported the core game module in the Forbidden Lands just created world, it creates the folders in the different sections of Foundry but no content is imported. An error is shown several times in the main screen:

![image](https://user-images.githubusercontent.com/75694733/122802517-bb6ff900-d2c5-11eb-9d47-d5401dac86f4.png)

**Comment by aMediocreDad** [comment]
Hi,

The module import scripts and macros are not yet compatible with 0.8+, as indicated by the compatibility risk. 0.8 had a lot of breaking changes which makes it incompatible with anything developed before it.

You can still import manually in bulk, but a better workaround is to use 0.7 to import and carry that world over to 0.8.

I am in the process of ironing out compatibility for 0.8 and I hope to have it ready sometime this week.

For future reference any issues and questions regarding the Official content modules should be made in a separate repository: https://github.com/aMediocreDad/fbl-content-modules

This repository is exclusively for the community developed system and is distinctly separate from the modules as such.

I will go ahead and close this issue as it is not related to the system.
