### ISSUE TITLE
🐛 Weapon/Armor wrong stats in player sheet

### ISSUE THREAD

**Issue by iarizex** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#139]
**Describe the bug**
The stats of the weapons/armor are OK in the item sheet. However, when dragged into the player's sheet, all the stats (such as modifier, damage, armor rating) seem to be 1.

**Expected behavior**
The stats of the weapons/armors when dragged into the player's sheet should look the same as the ones in the items.

**Desktop (please complete the following information):**
 - OS: macOS
 - Client Foundry Desktop app
 - Foundry Version 0.8.8

**Comment by WildBillLives** [comment]
I was coming here to post this very same issue, so I can confirm the above. In addition, all modifiers for items (such as the Move penalty for the heavier armors) are lost when you drop-n-drag the item to a character sheet.

**Comment by fgloppe** [comment]
And I complete: same thing for critical injuries. The modifier are not copied when drag&drop it to the character sheet

**Comment by aMediocreDad** [comment]
Hi! First of all, thank you for the report and follow ups. This issue will be solved in an upcoming patch.
