### ISSUE TITLE
🐛 Calendar/Weather support seems broken

### ISSUE THREAD

**Issue by Nedok** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#146]
**Describe the bug**
When starting a new world and activating *Calendar/Weather* no calendar configuration is done.

**Expected behavior**
When activating the *Calendar/Weather* module it should configure the calendar to the appropriate format for the forbidden lands.

**Desktop:**
 - OS: Windows 10
 - Nodejs client
 - Foundry Version ``0.8.8``
 - Forbidden Lands ``6.0.4``
 - About Time ``1.0.4``
 - Calendar/Weather ``3.1.6``
 - Simple Calendar ``1.3.8``

**Workaround**
Here a JSON file that can be imported into simple calendar to get similar calendar to the one used in the module:
https://pastebin.com/RGgyBHWX

**Comment by aMediocreDad** [comment]
Thanks! This will be fixed in an upcoming patch.

**Comment by aMediocreDad** [comment]
The author of Simple Calendar has been kind enough to incorporate the Forbidden Lands calendar as an option in the module. See latest release: https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v1.3.23

This is the best outcome at this point. Closing
