### ISSUE TITLE
Bug with damage calculation

### ISSUE THREAD

**Issue by JhaelenTerear** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#155]
When doing an attack roll, the first 6 rolled shouldn't count as damage : it allows the blow to hit the target. Currently, all 6 are added to weapon damage, to the result that the damage output in the chat card is always false : it should be one less.

Exemple : when attacking with a broadsword (damage 2), this roll result should have been 3 and not 4 : the first 6 allows the blow to hit (and thus inflicting the weapon damage - 2) and the other one adds 1 to the weapon damage for a total of 3, not 4.

![Capture d’écran 2021-09-07 195457](https://user-images.githubusercontent.com/58259514/132389818-df9fbd78-41ea-42d7-a711-17ab36cf16bd.jpg)

I hope I made myself clear, but if not, feel free to ask questions !

**Comment by aMediocreDad** [comment]
Hey! Thank you for logging this issue:) Yes, this was reported by some users from the Foundry Discord already. 

Raising the issue here helps with tracking, so thank you for that!

It'll be fixed in the next update.
