### ISSUE TITLE
Can't open Caractersheet 7.X

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#161]
### Discussed in https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **Lanistra222** September 11, 2021</sup>
Since the update to 7.X (7.0.3) I can't open the charakterhseets anymore. Affected ist just the charaktersheet not the monster-, party-or strongholdsheet. I tried to create a new world and occured the the same problem.</div>

**Comment by aMediocreDad** [comment]
Closed with 7.0.4

**Comment by aMediocreDad** [comment]
@Lanistra222 This is now fixed in 7.0.4

**Comment by Lanistra222** [comment]
Looks good. Thanks! Keep up the good work.
