### ISSUE TITLE
Typo in valuable find in lair

### ISSUE THREAD

**Issue by mogrogh** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#173]
**Checklist**
Before posting a bug make sure you have disabled all modules and checked if the issue is still present.
- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance.
- [X] Not a "How To"-question.

**Describe the bug**
<strong>Silver Statue</strong><br /><strong>Value: </strong>[[[[1d6]]]] gold<br /><strong>Weight: </strong>6

Too many [ and ] so the dice isn't rolled automaticly when this is rolled.

It's alternative 44 in the table.

**Comment by aMediocreDad** [comment]
Hey thank you for reporting this issue🙏🏼 This is the system's bug tracker, however, and so I kindly ask you to post any further issues you find in the [Module repository's bug tracker](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

I will move this report over to that repository and close it here.

Again, thank you for the bug report 👍🏼
