### ISSUE TITLE
✨ Support for VoiceActor by Blitz

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#176]
**Is your feature request related to a problem? Please describe.**
Currently [VoiceActor](https://foundryvtt.com/packages/VoiceActor) breaks in that the buttons on the header are not displayed. As reported by @moinen in the Foundry Discord.

**Describe the solution you'd like**
Allow the buttons to appear on the header as seen below.
![screenshot of a different systems header with the buttons](https://cdn.discordapp.com/attachments/751202281172762675/913167036430037022/unknown.png)

**Describe alternatives you've considered**
None.

**Additional context**
Screen above.

**Comment by moinen** [comment]
happens on actor sheet load
![bandicam 2022-04-19 11-10-26-391](https://user-images.githubusercontent.com/82953211/163970801-36d669a1-2150-4beb-9895-2201cf8fa991.jpg)

and this is on journal load
![bandicam 2022-04-19 11-14-08-798](https://user-images.githubusercontent.com/82953211/163971444-63ddb220-1b05-4edf-8042-5d48e4b61181.jpg)

**Comment by moinen** [comment]
VoiceActor is now compatible with FL system, thank you.
> 0.2.0 - 2022/04/26
> Updated for full compatibility with v9
> Added module setting for dark buttons for increased system compatibility
> Fixed overwriting issue - Module now records a fresh clip with a suffix counter. Be warned, if you overwrite the same clip a bunch of times, all of those clips will exist in your VA directory. You can safely delete the extras manually, the newest clip has the highest suffix number.
> Fixed caching issues, a side effect of the change above. Overwritten clips will now be available for playback instantly.
> Added support for **Forbidden Lands** (possibly some other modules too, if they do not use an actor property and instead make the _id directly available under data)

**Comment by aMediocreDad** [comment]
That's wonderful to hear! I'll close this one then.
