### ISSUE TITLE
Outdated module definitions in all official modules

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#180]
**Describe the bug**
Debug.log reports several outdated definitions in packages related to official content. Not sure what impact is currently, probably none, though in long run this might be problem.

```
{"level":"warn","message":"Package fbl-bitter-reach contains 6 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package fbl-core-game contains 8 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package fbl-core-game is using the old \"systems\" manifest key where a \"system\" key is expected","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package fbl-ravens-purge contains 6 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package fbl-ravens-purge is using the old \"systems\" manifest key where a \"system\" key is expected","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package forbidden-card-combat contains 1 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package forbidden-lands-party-sheet contains 2 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2021-12-27 10:47:38"}
{"level":"warn","message":"Package forbidden-lands-party-sheet is using the old \"systems\" manifest key where a \"system\" key is expected","timestamp":"2021-12-27 10:47:38"}
```

**Expected behavior**
No errors or warning in the logs.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 and macOS Monterey 12.1 
 - Client: Firefox & MS Edge, latest as of December 2021
 - Foundry Version: **9.238**

**Additional context**
n/a

**Comment by aMediocreDad** [comment]
Hi there!

Neither Forbidden Lands system, nor the official modules are compatible with V9 as of yet.

**Comment by SirPencil** [comment]
Is this still an issue with the 0.8.0 release?

**Comment by aMediocreDad** [comment]
> Is this still an issue with the 0.8.0 release?

Alright so let's dig into this. First of all, the official modules have not received an update for V9. That will come some time after the winter holidays are over (so mid January somewhere).

The final two modules `forbidden-card-combat` and `forbidden-lands-party-sheet` are not under my jurisdiction, they are maintained by someone else in the community (as such they are not official modules). In addition to that, the Forbidden Lands Party Sheet module is deprecated and only maintained for those on old Forbidden Lands installs. The Party Sheet was added to the system in version `5.1.0`. 

I'll go ahead and close this, as it is not relevant to the system itself and these deprecation warnings will be taken care of when the modules are being readied for V9.
