### ISSUE TITLE
Weapon actions in the character sheet should take into account weapon features

### ISSUE THREAD

**Issue by giant-teapot** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#19]
Rules state:
- only hook weapons can shove
- only parrying weapons can parry _without a penalty_

Currently, all melee weapon actions are displayed regardless of the weapon features.
It should be an easy change, I would be happy to tackle it or leave it for a new contributor.

**Comment by jimorie** [comment]
Yes, I agree this would be nice! I know that you mentioned implementing a better data model for the weapon features in your last PR, and I think that would be required before we can do this in a sensible way. Is that where you would plan to start as well?

In my long term vision we should also implement the different attack actions, slash and stab, based on weapon features. And then automatically apply the corresponding modifiers to dodge and parry rolls against the most recent attack. (Because I will never be able to learn those modifiers by heart...) 

As a sidenote you should still be able to parry with a non-parrying weapon, but it comes with a -2 penalty.

**Comment by giant-teapot** [comment]
Okay then, I'll try to give it a shot this week.

I'm not yet sure how I want to go about this (on the simple <-> sophisticated spectrum) but I'll make sure to keep you in the loop. Ideally I would roughly aim towards what @jimorie described, but going in small iterations.
I mean: I don't want to gift you a caffeine-powered, over-engineered, fuming pile of spaghetti. :)

**Comment by giant-teapot** [comment]
Sneak peak of the work in progress:
![feature_toggles](https://user-images.githubusercontent.com/477392/107874721-be904e00-6ebb-11eb-8714-08043541f9c8.PNG)

**Comment by aMediocreDad** [comment]
One thing that strikes me is that using radiobuttons in this instance confuses design language and UX. 

In the same sheet we have a decremental indicated by shading radio buttons, and a boolean indicated by shading for true. 

This is bad UX, and in a way it has been so in this case for a while. Starting with the attributes shading should have been done when an attribute point is "healthy" and not when it is damaged.

**Comment by giant-teapot** [comment]
@aMediocreDad That's a good point you're making. I never noticed how "checking" attributes/gear bonus was happening "backwards" (right to left). It's supposed to mimic how you check or fill a skull on the character sheet, but when I do it, it's always from left to right. A good point to keep in mind for later.

Now, regarding features and visual language, I agree it's not quite on par with standard expectations. I wanted to provide the same look as PC conditions. However I do agree: if it feels like a checkbox and quacks like a checkbox, then it should probably _be_ a checkbox.

![image](https://user-images.githubusercontent.com/477392/108103960-f4cff800-708a-11eb-9472-7023f75aa34c.png)

Hope you like it better. I certainly do. :)
I was busier than I thought lately, but I'm slowly making progress. There's more to come. I'll post a draft PR when I feel I'm "almost there".

**Comment by aMediocreDad** [comment]
This looks a lot less confusing:)

I hope to clean up the design language once a redo of the sheet layouts are on the way. 

The system is already a bit all over the place in terms of UX at the moment so not to worry too much:)

**Comment by jimorie** [comment]
First, nice work @giant-teapot!

Second, I think you're both crazy! 😅 To me it makes complete sense to "cross off" attributes from right to left -- you mark the damage to the attribute. Seriously though, I guess it's just two different ways of looking at it and neither is right or wrong.

**Comment by aMediocreDad** [comment]
> To me it makes complete sense to "cross off" attributes from right to left -- you mark the damage to the attribute.

I certainly understand how this feels right. To me, it's that I see them as radio buttons. 

If they were filled with black and you crossed them out from right to left I would have less of an issue I think.

**Comment by aMediocreDad** [comment]
I was thinking something more along these lines.

![image](https://user-images.githubusercontent.com/9851733/108185266-68661980-710c-11eb-928b-ddcb75bf214b.png)
