### ISSUE TITLE
Sheets Broken in Safari on Mac

### ISSUE THREAD

**Issue by Rentagurkha** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#212]
The actor, item and monster sheets do not render in Safari for Mac (macOS 12.3, M1). See attached file. This occurs on both my hosted site and when I run it locally. The problem does not occur on Chrome.
<img width="882" alt="Screen Shot 2022-03-27 at 11 24 19 AM" src="https://user-images.githubusercontent.com/102476430/160288701-8526c26c-82f8-4a3b-8e94-0d3ee318fec8.png">
<img width="549" alt="Screen Shot 2022-03-27 at 11 24 58 AM" src="https://user-images.githubusercontent.com/102476430/160288710-dc3fd5c4-099a-4c32-adf3-1aa9b7aa45ba.png">

**Comment by aMediocreDad** [comment]
Hi, yes. The unfortunate reality is that Safari is way behind on browser support for commonly used syntax like Regular Expression syntax that is being used in this system: https://caniuse.com/js-regexp-lookbehind

I am unfortunately not willing to work around Safari's lack of support in this instance. And I suggest you continue using Chrome (or FireFox if absolutely necessary).
