### ISSUE TITLE
🐛 Chargen Minstrel

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#216]
> As reported by @lordwey in https://github.com/aMediocreDad/fbl-content-modules/issues/15

When the event "Enlisted" was selected, it is missing the shortbow and the D8 arrows resource. Currently in the cord module it is missing this gear.

**Comment by narukaioh** [comment]
I will see it, if you didn't started it yet
