### ISSUE TITLE
✨ Issue title goes here

### ISSUE THREAD

**Issue by Gvicross** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#217]
Please, make a Initiative Tracker realy usual. Savage Worlds it's perfect, run completely loyal to the set rules. FL just dont work to me, need other modules like Reverse Initiative Order and a macro and ever, a repeat number just break the flux of game, and I have to reroll.

**Comment by aMediocreDad** [comment]
Hey! Which version of the game are you on? The latest version features an initiative tracker that only rolls unique numbers from 1-10 (or the max you set in settings). It also orders by ascending numbers. Lets you duplicate combatants (for monsters with several initiative counts). You also have toggles for fast and slow actions.
