### ISSUE TITLE
✨ Add description field to normal Weapons & Armors

### ISSUE THREAD

**Issue by moinen** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#218]
**Is your feature request related to a problem? Please describe.**
I would love to be able to add custom descriptions to Weapons and Armors, but as for now it is only possible with Special or Artifact category. 

**Describe the solution you'd like**
Ad Description field or make Features field auto expand

**Additional context**
You cannot use the features field for this purpose - it doesn't auto expand
![image](https://user-images.githubusercontent.com/82953211/163969284-b40c8b00-4782-476c-b2b9-5f17faf54fac.png)
This would be the perfect solution
![image](https://user-images.githubusercontent.com/82953211/163969416-5040c77e-5dd0-447b-ad53-2d15f457b665.png)

**Comment by aMediocreDad** [comment]
The features field is meant for features only. I can make the features field a text field instead so it can accomodate that text. If you want to add a Description to the weapon or armor use the "Special" option in the Artifact dropdown. This will not make it an Artifact, but still add the artifact fields in like Description, Drawback Effect and so on.

**Comment by moinen** [comment]
I know that features field is, well, for features, but it seems to be the easiest change to make. Like you said, to change it to a text field.
"Special" option is great but in this case suboptimal because you loose the Craft and Supply tab.

**Comment by narukaioh** [comment]
We do not have weapons with custom descriptions in the player's handbook. This field does not exist in the dynamics of the game.

If your weapon is different, let's say it's already "special" in its own right.

I think it makes more sense to take advantage of the field than to add a description field that doesn't exist.

One thing I also think is that if we can save the system of having more fields in the interface, we can have a cleaner interface.

**Comment by moinen** [comment]
Fair enough. What about the idea of just making it a text field so it autoexpands?

**Comment by narukaioh** [comment]
> Fair enough. What about the idea of just making it a text field so it autoexpands?

There is already something you can add the information to, just use that option I mentioned in the other comment
