### ISSUE TITLE
✨ Compatibility with ItemPiles

### ISSUE THREAD

**Issue by moinen** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#221]
**Is your feature request related to a problem? Please describe.**
Support for putting items as tokens on the ground would be another improvement.

**Describe the solution you'd like**
Just file the system request for the [ItemPiles](https://github.com/fantasycalendar/FoundryVTT-ItemPiles) module.

**Comment by narukaioh** [comment]
This module works, but it has some considerations. We do not use the system to count by "quantity" of items, but by the weight it provides. However, I can show you how you can configure a token so that it can serve as a chest.

**Comment by narukaioh** [comment]
<img width="584" alt="Screen Shot 2022-06-05 at 08 21 12" src="https://user-images.githubusercontent.com/359991/172048107-e89a2436-957a-4c39-9bf9-c8137bfcc2c4.png">

**Comment by moinen** [comment]
This is looking great! With these setting the trading works. You can even trade talents so it looks super fun.
The currencies are the only thing left. What settings should I input?

**Comment by moinen** [comment]
done
![image](https://user-images.githubusercontent.com/82953211/172373145-25154068-378e-4956-bfc2-0c7ebcfe75e8.png)

**Comment by moinen** [comment]
only similarities and filters

**Comment by narukaioh** [comment]
I think we can close this issue, right?

**Comment by moinen** [comment]
I'm not sure. It is solved for me only. The solution is to fill the form for ItemPile dev so the module can support FL system natively.

**Comment by narukaioh** [comment]
> I'm not sure. It is solved for me only. The solution is to fill the form for ItemPile dev so the module can support FL system natively.

so the itemPile that should inform how to configure it for forbidden lands, we try to support the modules that interact directly with the system mechanics.

for example, calendar, reverse initiative, and so nice dice.

some time ago I made a PR for an animation module to be able to support the Forbidden system, on our side of the system we don't need to do absolutely anything, but the module in question.

This does not seem to me to be a need for the system, but rather an interest for the module team
