### ISSUE TITLE
Case-insensitive artifact dice

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#24]
As per discussion #23.

### Expected behaviour:

 - Input "D12" in roll modifier or input and roll a d12 artifact dice.

### Actual behaviour:

- Does not recognize uppercase "D".

This should be an easy fix.

**Comment by jimorie** [comment]
Created a PR for this: https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/pull/29
