### ISSUE TITLE
k is not defined when attempting to Update all

### ISSUE THREAD

**Issue by GreyBeardUK** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#252]
### Describe the bug

When I attempt to patch the Forbidden Lands game system I get the following displayed in the Package update log

Package                   Result      Description 
Forbidden Lands     Error        K is not defined

### Reproduction

Removed all Game Worlds
Clicked on Game Systems
Installed the Forbidden Lands
Click Update all
error appears

### System Info

```shell
Mac OS
Using Molten Hosting
Foundry version:  Version 9 - Build 269
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
This is related to the manifest in the new release not being readable by V9. Foundry is coming with an update that should fix this.

**Comment by EternalDeiwos** [comment]
@GreyBeardUK you can grab a link to the [9.2.2 release `system.json`](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/download/v9.2.2/system.json) from the Github Releases and feed that to foundry to update v9
