### ISSUE TITLE
[V10] Editors: Can't save text

### ISSUE THREAD

**Issue by Cador2** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#261]
### Describe the bug

i cant save any text, for example in the bio of the hero, or in journal entries.

### Reproduction

just load a new word, create an actor and try to type smth in his bio

### System Info

```shell
os windows 10
latest foundry update for the desktop app
```

### Logs
that is the error when i try to save the bio
24foundry.js:5920 Uncaught (in promise) Error: system.bio.pride.value is not an active editor name!
    at ForbiddenLandsCharacterSheet.saveEditor (foundry.js:5920)
    at jR.save_onsavecallback (foundry.js:5962)
    at plugin.min.js:4
    at jR.<anonymous> (plugin.min.js:4)
    at commands.exec.<computed> (tinymce.min.js:4)
    at iR.execCommand (tinymce.min.js:4)
    at jR.execCommand (tinymce.min.js:4)
    at Object.onAction (plugin.min.js:4)
    at theme.min.js:4
    at theme.min.js:4

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by skeet70** [comment]
I have the same problem, this is the error I get when I try to save a journal entry

```
Uncaught (in promise) Error: text.content is not an active editor name!
[No packages detected]
    saveEditor http://192.168.0.59:30000/scripts/foundry.js:5977
    onSave http://192.168.0.59:30000/scripts/foundry.js:6068
    _handleSave http://192.168.0.59:30000/scripts/prosemirror.js:15328
    _onAction http://192.168.0.59:30000/scripts/prosemirror.js:15301
    onclick http://192.168.0.59:30000/scripts/prosemirror.js:14854
```

![image](https://user-images.githubusercontent.com/1424117/189458227-ef1b4007-874d-4d78-9855-6c0ef1918516.png)
![image](https://user-images.githubusercontent.com/1424117/189458354-59fee4f6-3121-49d3-9f72-d9630759480b.png)

All the journal controls are fully horizontal and expanded as well.

**Comment by skeet70** [comment]
This may be related to #250 but I'm not sure if these are the alternative sheets or not.

**Comment by skeet70** [comment]
Confirmed that [0e92817](https://github.com/aMediocreDad/forbidden-lands-foundry-vtt/commit/0e9281787b34425efff350eac5191ff77c9d872c) fixed the saving issue, and also makes the formatting controls show up in a sane way. Editing old journal pages still seems to have some weird text display issue. For reference:

Page created and edited in v10:
![image](https://user-images.githubusercontent.com/1424117/191097170-e9ee9a1b-a9c5-4209-8945-091b400b9ebd.png)

Page created in v9 and edited in v10:
![image](https://user-images.githubusercontent.com/1424117/191097264-cbe4985e-f15f-45f6-a4e1-56e92ef713a2.png)
![image](https://user-images.githubusercontent.com/1424117/191097336-4653703e-2d66-422a-98cb-47f9e8daafc4.png)
