### ISSUE TITLE
[V10] Critical Injuries Macro not sending to chat

### ISSUE THREAD

**Issue by tak5haka** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#263]
### Describe the bug

Using the Critical Injuries macro, the dialog box pops up as expected but the results are not passed to chat. 

See logs for error messages

### Reproduction

Click on Critical Injuries macro, choose a damage type.

### System Info

```shell
macOS
Foundry Desktop app
Foundry version 10.285
Forbidden Lands version 10.0.0-2
```

### Logs

Console reports the following non-critical errors:

```
Error: You are accessing the TableResult#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1245:19)
    at TableResult._logV10CompatibilityWarning (commons.js:6166:14)
    at get data [as data] (commons.js:6066:24)
    at sendToChat (eval at _executeScript (foundry.js:19982:16), <anonymous>:11:50)
```

And the following critical error:

```
VM1141:13 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendToChat')
[No packages detected]
    at sendToChat (eval at _executeScript (foundry.js:19982:16), <anonymous>:13:39)
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
Is this the macro that follows the Official content modules?

**Comment by tak5haka** [comment]
Now that you mention it, I've gone back into the v10 install and it is one of the macros from the Core Game module, so that could be the reason why. I initially thought it was part of the system rather than a module.

**Comment by aMediocreDad** [comment]
Moving this to the correct repository.
