### ISSUE TITLE
Unable to update Game System in Foundry with Foundry Version 10 - Build 285 (Testing channel) 

### ISSUE THREAD

**Issue by gevrik** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#264]
### Describe the bug

<img width="1159" alt="Screenshot 2022-09-15 120255" src="https://user-images.githubusercontent.com/1548475/190376773-bd9ae83f-576c-4b86-ad93-8a268689ade5.png">

This is what Foundry shows when trying to update the game system.

### Reproduction

Update Foundry to version 10 - Build 285 in the Testing channel

### System Info

```shell
Foundry Version 10 - Build 285 (Testing Channel)
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by Bapf** [comment]
(Still the) Sam on v10 (stable)
