### ISSUE TITLE
V10 - Unable to edit Talent text field

### ISSUE THREAD

**Issue by Squiggatron** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#266]
### Describe the bug

I am unable to edit existing Talent text.

### Reproduction

With an existing Talent, I am simply unable to click the pencil icon that allows editing of text. If I create a new talent, I can edit the text field, but only once. Once I save the text, I can no longer make edits.

### System Info

```shell
OS: Win10
Client: Foundry Desktop App
Foundry v10.286
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by Abdanck** [comment]
By any chance will it be corrected for the next release ?

**Comment by aMediocreDad** [comment]
Sorry this has taken a while. I am unable to reproduce this issue, try as I might. Could you verify that you are on version 10.0.0-4? And the latest version of Foundry? Also a screenshot or better yet screencapture of the issue would help greatly. Finally, make sure there are no modules running that might interefere with the style of the edit button.

**Comment by Abdanck** [comment]
I've tried to show the bug in a short video : https://1drv.ms/u/s!AlWlskovkH_FjNFgRnluM5P48Dzf3g?e=X2MajC
