### ISSUE TITLE
Journal Text Edit Misalignment

### ISSUE THREAD

**Issue by Ralkiin** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#268]
### Describe the bug

When in the text editor of the new v10 journal system text will misalign and overlap. This can compound and make text editing very difficult. Whenever the text is saved, it appears normally in the journal.

### Reproduction

1) Edit a journal page.
2) Shift+Enter down half of your viewing window.
3) Press Enter
4) Start a bulleted list.
5) Hit enter to make multiple lines for the bulleted list.

### System Info

```shell
-Windows 10
-Desktop App
-Foundry Version 10, build 288.
-Forbidden Lands System 10.0.0-4
```

### Logs

4foundry.js:5058 Foundry VTT | Rendering JournalSheet
foundry.js:6845 Foundry VTT | Retrieved and compiled template templates/sidebar/document-create.html
foundry.js:5058 Foundry VTT | Rendering Dialog
foundry.js:6845 Foundry VTT | Retrieved and compiled template templates/hud/dialog.html
game:1 Autofocus processing was blocked because a document already has a focused element.
foundry.js:5058 Foundry VTT | Rendering JournalTextPageSheet
commons.js:6921 Foundry VTT | Created JournalEntryPage with id [OXrF38COXqkprc1Y] in parent JournalEntry [VHZ1FPyp5wlm0lt8]
foundry.js:6845 Foundry VTT | Retrieved and compiled template templates/journal/page-text-edit.html
foundry.js:5058 Foundry VTT | Rendering JournalSheet
foundry.js:5058 Foundry VTT | Rendering Dialog
foundry.js:5058 Foundry VTT | Rendering JournalTextPageSheet

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
This is related to Prosemirror, removing CSS rules for the editor solved the issue. Should clean up some of the css anyway.
