### ISSUE TITLE
Error installing new version 10.0.2

### ISSUE THREAD

**Issue by JECHRA** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#275]
### Describe the bug

Hello,
Facing below when installing version 10.0.2
setup.js:292 Error: Unable to load valid system manifest data from "https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/latest/download/system.json"
The requested manifest at "https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/latest/download/system.json" did not provide system manifest data.
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1620)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

### Reproduction

Installing new version 10.0.2

### System Info

```shell
Windows 11
Foundry Desktop app
Foundry version v10.288
```

### Logs

setup.js:292 Error: Unable to load valid system manifest data from "https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/latest/download/system.json"
The requested manifest at "https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/latest/download/system.json" did not provide system manifest data.
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1620)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
This is correct behaviour, from which version are you attempting to upgrade?

**Comment by aMediocreDad** [comment]
If this is a fresh install then you might have a cache issue with the platform. I'd recommend restarting Foundry then attempting a clean install of the system again. 

What Foundry is using as a source in your issue above is an old manifest. The new manifests were uploaded about a day and a half ago to Foundry admin: https://foundryvtt.com/packages/forbidden-lands

**Comment by JECHRA** [comment]
Version I currently have is 10.0.0-4

**Comment by aMediocreDad** [comment]
> Version I currently have is 10.0.0-4

Then please uninstall and reinstall the system again in your foundry instance. The alpha versions were on an old update track.

Uninstalling the system itself confers no dataloss. But nevertheless always make sure you have a backup.

**Comment by JECHRA** [comment]
Using the link from https://foundryvtt.com/packages/forbidden-lands and it is working
The link on https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt is not working

**Comment by aMediocreDad** [comment]
> The link on https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt is not working

Thanks for the heads up. I completely forgot about the link in the Readme. Will proceed to update the Installation instructions.
