### ISSUE TITLE
Armor and Gear Artifacts

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#28]
As the 'artifact' item type has been removed and integrated into the 'weapon' item type, we no longer have a good place for non-weapon artifact types. _Barkhyde_, for example, is a helmet (kind of). It would fit best into the armor category, mechanically, but there's currently no way to properly add its effects, drawbacks, etc. there. Entered as an artifact weapon, it gets placed into the 'weapons' slot on a character sheet, and of course lacks a way to track armor rating there as well.

Is there currently a plan to revise the armor item sheet to allow for artifact types? There are also a fair number of artifact items that don't really fall well into either category and should maybe considered more as artifact 'gear' (_Clay's Rosary_, for example).

_Originally posted by @rwisaak in https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions/27_

**Comment by giant-teapot** [comment]
Do you need help with that? Do you think of any preliminary cleanup/improvement that would make this task simpler?

**Comment by aMediocreDad** [comment]
Would be great with some help on it:) 

I don't expect to initiate the refactoring of the dev environment before content modules release... which is still some distance away. 

I'd rather have this issue fixed before that.

**Comment by aMediocreDad** [comment]
@giant-teapot I have opened a branch for this issue: https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/tree/Artifact-Arrmors-and-Gear
