### ISSUE TITLE
Static Sheet Button Text

### ISSUE THREAD

**Issue by FolkvangrForgent** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#306]
### Description

The current buttons on sheet views are show in a compact mode that only shows the associated text when hovering over the button. I personally find that the buttons are more accessible when the buttons do not resize and also describe what they do without having to hover over them.

### Suggested solution

Perhaps a toggle within the system setting could change the behavior of the button text, this would maintain both ways of displaying the buttons. I have not looked into what is causing the behavior of the current buttons to comment any more.

### Additional context

Below is a mock-up of the sheet with static text created by mucking around with the css ( I also changed the margin-left to 4px for the button image as I think it helps associate the text more with the button in this sort of static view)
![image](https://user-images.githubusercontent.com/25625121/231343247-3589a006-d91d-4a98-8376-574ff9235474.png)

### Validations

- [X] Not a feature request for the official content modules. Issues regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aMediocreDad** [comment]
In the most recent release I made the text into tooltips instead. There were originally a few more buttons there so it ended up being too crowded. Though I can certainly add a toggleable functionality that makes these buttons more accessible.
