### ISSUE TITLE
New journals headings too deep (v10.2.0)

### ISSUE THREAD

**Issue by tak5haka** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#309]
### Describe the bug

Have just updated to latest version of the Forbidden Lands system and am testing it on my local install. I notice that the new style top header block is very deep with a lot of white space, which means when this is combined with the section/page heading, it takes up nearly half the height of the page before you get to the important text (see "New Heading Block Default Height").
![New Heading Block Default Height](https://user-images.githubusercontent.com/40823406/235781556-e7064484-8189-4a68-9aec-f4784c6193d5.png)
I have fixed this on my local install using the Custom CSS module as follows:
`.app.window-app.sheet.journal-sheet input[name="name"] {
	min-height: 60px;
	padding-top: 0;
}`
This results in the display as shown in "New Heading Block Revised Height", attached, which looks better to me.
![New Heading Block Revised Height](https://user-images.githubusercontent.com/40823406/235781962-6d7e1aa2-cc80-4e34-ad35-003bb04f1fcd.png)
Might I suggest reviewing this to see if the `min-height` command needs to be updated to reduce the height?

### Reproduction

Update to the latest version of the Forbidden Lands module (v10.2.0) and open any journal.

### System Info

```shell
OS: macOS
Client: Foundry Desktop app
Foundry version: 10.291
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by tak5haka** [comment]
Good point - I had both Raven's Purge and Bitter Reach modules activated. It was pulling this from the Bitter Reach style sheet (line 27, `.app.window-app.sheet.journal-sheet input[name="name"]`). Once this is deactivated, the issue resolves itself for the core module. Activating the Raven’s Purge module has no effect. Activating the Bitter Reach module causes the display issue.

**Comment by aMediocreDad** [comment]
Great! Thanks for digging. I will close this some time after the module updates are out in case anyone comes by looking for this problem.

**Comment by tak5haka** [comment]
Just did an update of the content modules and it all looks good to me now.

Many thanks for all your hard work on these, it really makes a difference to running and playing the game and is appreciated.
