### ISSUE TITLE
Title of Mishap Tables for Hunting Mishaps.

### ISSUE THREAD

**Issue by tak5haka** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#315]
### Describe the bug

This isn't really a bug, just an observation. On the new table configuration sheet (which is great, by the way) in the "Mishap Tables" list, the title for the Hunting Mishaps is labelled "Find Prey" and I presume this should say "Hunting" to match the others in the list? 

### Reproduction

Open the Table Configuration sheet, see the screenshot below.
![Table Configuration Sheet](https://user-images.githubusercontent.com/40823406/236042547-026bce7f-7c4b-4cfa-aa49-7cf3323837b9.png)
I am presuming it should say "Hunting" here instead of "Find Prey"?

### System Info

```shell
OS: macOS
Client: Foundry Desktop app
Foundry version: 10.291
System version: 10.2.1
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
Thanks! You are right. It should say "Hunting".
