### ISSUE TITLE
Option to disable FL window style

### ISSUE THREAD

**Issue by Mishokkka** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#402]
### Description

Some of the modules in Foundry VTT create all kinds of windows themselves. The main flaw is that they do not account for worn paper style, that is applied to all of the windows inside of the game world. Usually it creates just visual issues without serious drawbacks, but for some of the modules (especially with small windows) the paper texture on the edges covers some of the fields.
![изображение](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/assets/43003510/e8e7fe2b-8d07-40b4-b704-23e4226920de)

### Suggested solution

Make this stylization an option in the settings of the module. When enabled - it affects all of the windows as usual, when disabled, it leaves the edges untouched, with straight line window edges.

### Alternative

None that I can think of.

### Validations

- [X] Not a feature request for the official content modules. Issues regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aMediocreDad** [comment]
This is now a setting in the new update.
