### ISSUE TITLE
Minus modification doesnt subtract dice

### ISSUE THREAD

**Issue by SwedishRabbit** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#404]
### Describe the bug

Player  puts -1 in the "modification menu" for the weapon.  Foundry instead ADDs one die to the dice pool.

### Reproduction

Player is in battle. He has to use his weapon with a minus modification. He puts -1 in the "modification menu" for the weapon. Presses the buton "Roll dice". Foundry instead ADDs one die to the dice pool.

### System Info

```shell
Foundry VTT 11.315
Forbidden Lands v11.4.2
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
If there are no skill dice the system will add Negative dice to the rolled pool. If there is a skill die, it will subtract.

This is the expected outcome, and also verified when testing.

Could you please provide more context? E.g. a video or screenshots showing the interaction.

**Comment by SwedishRabbit** [comment]
Ahh .. I realize - my bad! 🥴 I misunderstood the dice pools rules for subtracting... Please close this thread.
