### ISSUE TITLE
Item Gear Bonuses buggy

### ISSUE THREAD

**Issue by bblonski** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#409]
### Describe the bug

I've noticed 2 different bugs around roll modifiers from gear/talents. When I have a talent like swordfighter and I level it up to give a +1 and a +d8, I modify the Roll Modifier to match. However if I set the dice code to `1+d8`, I'll only the d8 is applied when selecting it from modifiers in the roll dialogue. The +1 is missing from the modifiers section, and has to be entered manually. However, if I change the code to `d8+1`, it properly applies the d8 and +1 to the roll modifiers.

The second issue is if you enter a dice code (e.g. d8) into the roll modifier, but the check "Use Gear Bonus", you'll see d8 code as the modifier in the roll dialog, and if you try to roll with it selected, you'll get an error like the following.

```
Uncaught (in promise) Error: Invalid roll formula: 3db[Wits] + 2ds[Lore] + NaNdg[Maidenshard] + 1d8[Gear]
    at FBLRoll.forge (forbidden-lands.js:17:40697)
    at _FBLRollHandler.executeRoll (forbidden-lands.js:17:35837)
    at _FBLRollHandler._handleYZRoll (forbidden-lands.js:17:33542)
    at _FBLRollHandler._updateObject (forbidden-lands.js:17:31866)
    at _FBLRollHandler._onSubmit (foundry.js:6626:18)
```
I assume it's hiding the d8 instead of deleting it, then when it comes time for the roll, the formula is getting confused on what the gear dice should be.

### Reproduction

Bug 1
- Create a Gear named Test.
- Give it a roll modifier to Animal Handling of `1+d8`
- Add this talent to a Character
- Click the Animal Handling Skill and select the Test from modifiers.
- The d8 is entered under Artifacts, but the +1 is missing under Modifiers.

Bug 2
- Modify the Test gear to give it a gear bonus of 1.
- Modify the roll modifier to be `d8`
- Click the "Use Gear Bonus" check on the roll modifier.
- Click the Animal Handling Skill.
- The modifier from Test is listed as `d8`.
- Select the Test modifier and click Roll.
- Dice are not rolled and you get a console error.

### System Info

```shell
OS: Linux Host, Windows Client
Client: Chrome
Foundry Version: 11 build 315
Forbidden Lands Version: 11.5.0
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by aMediocreDad** [comment]
Bug 1. Is simply using it incorrectly. The modifier field does not handle arbitrary expressions. The correct way of going about it is to add two separate roll modifiers +1 and 1d8.

Bug 2. Is definitely something that needs to be looked into.
