### ISSUE TITLE
Character Gen characters have an automatic 2 on encumbrance at generation

### ISSUE THREAD

**Issue by newbyr** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#456]
### Describe the bug

When a new character is generated though the character generator, even if you take off all the gear, it has an encumbrance of 2. 
![image](https://github.com/user-attachments/assets/6f7fc897-cbda-4dd9-ae82-0a38a5f0ad74)

### Reproduction

Start a new actor.
Select Chargen
Accept generated character
Go to Gear tab.  Gear listed is +2 compared to that listed
Remove all gea, and emcumbrance is reported as 2 - should be 0

### System Info

```shell
Linux
Foundry 12.331
Forbidden Lands 12-1-0
```

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by Raldanash** [comment]
Did you also drop food and water to 0 dice? If there is any die in any consumable, it counts as 1 encumbrance

**Comment by newbyr** [comment]
No.  These are not included in gear in the rules.  Gear encumbrance is only
items

**Comment by Raldanash** [comment]
p 38 Player Handbook. Just tested it on my foundry and if you take the resource dice off a generated character (and all the other kit), encumbrance drops to 0.

**Comment by newbyr** [comment]
Thanks, I'll check it out!

**Comment by newbyr** [comment]
My error.  Thanks

I'll close bug

**Comment by newbyr** [comment]
closed
