### ISSUE TITLE
Refactoring of Dev Environment

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#58]
Changes include: 
- Automatized Gulp workflow.
- CSS -> SCSS (for faster maintenance).
- JS -> TS (this is a slow change, but one that will allow for Foundry.js type definitions and documentation. It will also facilitate creating unit tests).
- Prettier code formatting.
- Github Actions.
- Reorganization of files and folders.

**Comment by giant-teapot** [comment]
Oh, that sounds yummy! :yum: 
Do you know how you are planning to roll this out?

Even putting aside the positive effects for those technical changes, it could be an opportunity to learn new stuff. For instance I never really got an opportunity to play out with TS in any meaningful way.
So… if you think of means to offload some of that burden to a pretty ignorant but happy to learn lemming… yeah, let me know. :)

**Comment by DavidCMeier** [comment]
Uau!! That's amazing! Nice job :D 

You just translate js to ts, no? 

Because i think that we can improve the refactor like don't used let, use .forEach or map instead classic bucle for, etc.. etc...

If you need help with this i can make something :) Probably now in my holidays

**Comment by aMediocreDad** [comment]
Would love any help I can get on this:) 

> You just translate js to ts, no?
At the moment, yes.

After some consideration I think I will drop TS for now. There are several factors playing into this. First and foremost the Foundry team have decided to fast forward 0.8.x release and during testing of 0.8.x I have found several issues which needs to be fixed to get the system ready for the next beta. In addition, the type library for 0.8 provided by the Foundry Dev Community is far from a usable state which puts a huge dampener on the whole conversion. 

I am hoping to convert later down the line when there is less likelihood of major breaking changes to the type libraries.

Still I will go ahead and rearrange and make CI/CD a lot more efficient. Also slowly moving over to SCSS for easier maintenance of styling.
