### ISSUE TITLE
#71 Add support for Safe Casting and Ingredients.

### ISSUE THREAD

**Issue by aMediocreDad** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#72]
As seen in #71, the dice roller for spell casting can seem a bit confusing if one assumes that you can include Ingredients and Safe Casting in the dice roll.

Adding support for these via checkboxes or similar adding to the total power level without displaying dice would probably make the whole process a lot more intuitive.

**Comment by narukaioh** [comment]
do you want a suggestion about this feature or do you knows about the how someone can implementation this one?

I would like to work on this card, it seems very useful.

**Comment by aMediocreDad** [comment]
> do you want a suggestion about this feature or do you knows about the how someone can implementation this one?

After this release and the history rewrite I'll go back to the drawing board on implementing the new [YZUR](https://github.com/Stefouch/foundry-year-zero-roller). 

It means refactoring the logic behind all the roll dialogs. 

This will take some time, but a side effect should be that this issue will be fixed.

**Comment by narukaioh** [comment]
Well, do you intend to do all the work yourself?

It would be interesting that after your analysis, you could write cards of what you need to refactor.

So other people could help, and maybe be able to gain more context from the project

**Comment by aMediocreDad** [comment]
> Well, do you intend to do all the work yourself?

It's actually done. That said, I am not happy with it and I am not sure where I want to go with it at the moment. 

The issue isn't so much writing the logic as it is figuring out how I want to go about it.

What I want to support is:

- Attribute, Skill/Action, Gear/Weapon rolls with push and applying damage on push, as well as applying Talent/Gear modifiers dynamically.
- Futureproofing the above for extending into contested rolls.
- Spell rolls with support for what is mentioned in this issue.
- Consumable rolls without dialog.

All of the above should also be dynamic enough that if you wanted to you could add homebrew.

One could certainly split this up, but I want the design of each component be identical in nature so I don't have to deal with a bunch of diverging design choices in the respective implementations. E.g. one dev using `for i++` loops another `for in`, a third `forEach` and the fourth `for of`.

**Comment by aMediocreDad** [comment]
This feature has now been rolled into the system. Closing
