### ISSUE TITLE
Character Generator

### ISSUE THREAD

**Issue by MichalKolesinski** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#95]
First: warning message. I believe that the sentence should sound: "Clicking .... with no way to revert the changes". It's actually possible to to reset the changes again and again by generating new character, but there's no option to go back, so I guess that word "revert" fits better than "reset".
![screenshot3](https://user-images.githubusercontent.com/39199872/115288259-86261e00-a151-11eb-9f26-d6d8efced27c.png)

Second: When the character is generated one can click on "apply" several times, spawning copies of equipment and talents. One click should do the job. Next click should work if the character would be generated again.
![Screenshot4](https://user-images.githubusercontent.com/39199872/115289210-9e4a6d00-a152-11eb-9fe4-b447172b180f.png)

**Comment by aMediocreDad** [comment]
Hi,

First, I concur. Revert is a better word here.

Second, is a bug (the chargen should close). I will have it fixed in the next update.

**Comment by MichalKolesinski** [comment]
Hi! One more thing about character generator. It allows to generate young and old elf. It shouldn't be possible, since they don't age normally and for the game purposes they count as adults. (p. 31 in players handbook, p. 2 step 8 in the booklet)

**Comment by aMediocreDad** [comment]
> Hi! One more thing about character generator. It allows to generate young and old elf. It shouldn't be possible, since they don't age normally and for the game purposes they count as adults. (p. 31 in players handbook, p. 2 step 8 in the booklet)

This one proved a bit tricky to get around, but I have a working fix for this one.
